name: secretaria
description: Utilities for assholes.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0-89.0.dev <4.0.0'

# Add regular dependencies here.
dependencies: 
  path: ^1.8.3
  # path: ^1.8.0
  #sid_d_d:
  #  path: 'D:/DEVS/sid_d_d'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
